# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f3c8cc415da681e8423eaef6a6f4966d9f3bb07cacb1fed8768b80b4d808bcf28b88b3664a3bf18adae913969df9a048a3d48f8fcb935eb41e4d8a01bcaf56

test:
  secret_key_base: 874f278f870893ea13540e369d0e51cde9711c8718f47174f28940293923d871587566cee79a6bbf0815bd1fdb3e4ae286103d1e060a404ae50dbf357e47bb5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
